### ISSUE TITLE
ImportError: No module named 'six'

### ISSUE THREAD

**Issue by Kokiro** [bprinty/Flask-Authorize#23]
```
Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from app import create_app
  File "/app.py", line 5, in <module>
    from extensions import db, bootstrap, login_manager, authorize
  File "/extensions.py", line 4, in <module>
    from flask_authorize import Authorize
  File "/Documents/VirtualEnvs/xyzy/lib/python3.4/site-packages/flask_authorize/__init__.py", line 11, in <module>
    from .mixins import RestrictionsMixin           ## noqa
  File "/Documents/VirtualEnvs/xyzy/lib/python3.4/site-packages/flask_authorize/mixins.py", line 10, in <module>
    import six
ImportError: No module named 'six'
```

**Comment by bprinty** [comment]
Good catch - just pushed a change adding `six` in the `requirements.txt` file.
