### ISSUE TITLE
VARCHAR requires a length on dialect mysql

### ISSUE THREAD

**Issue by ttpcodes** [bprinty/Flask-Authorize#38]
I've set up my application to use `MySQL` as the database, but when I try to make my Group model extend `AllowancesMixin`, I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2895, in visit_create_table
    create_column, first_pk=column.primary_key and not first_pk
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 95, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2928, in visit_create_column
    text = self.get_column_specification(column, first_pk=first_pk)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 1562, in get_column_specification
    column.type, type_expression=column
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 400, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 95, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3438, in visit_type_decorator
    return self.process(type_.type_engine(self.dialect), **kw)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 400, in process
    return type_._compiler_dispatch(self, **kw)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 95, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3416, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2035, in visit_VARCHAR
    "VARCHAR requires a length on dialect %s" % self.dialect.name
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql
```

It seems that manually editing the `mixins.py` file from this package and setting the length of the String on the JSON type manually fixes the problem.

**Comment by bprinty** [comment]
Thanks for the heads up! Just PR'd a fix and released a new version (0.1.8) to PyPi.

https://github.com/bprinty/Flask-Authorize/pull/39
